### ISSUE TITLE
Sample project does not work with Django 2.0.9

### ISSUE THREAD

**Issue by wooyek** [caktus/django-treenav#74]
```
Django==2.0.9
django-js-asset==1.1.0
django-mptt==0.9.1
-e git://github.com/caktus/django-treenav.git@8f81619a8598790d1c2dc7bf77ba9d8e9e9564e6#egg=django_treenav
pytz==2018.7
```

```
!   ³ django-treenav  /d/w/g/django-treenav   develop  sample_project  ./manage.py  migrate                                                         
Traceback (most recent call last):
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/urls/conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 58, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/data/venvs/django-treenav/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/data/work/github/django-treenav/sample_project/urls.py", line 8, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "/data/venvs/django-treenav/lib/python3.5/site-packages/django/urls/conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
```

**Comment by xyzmes** [comment]
What is your urls.py?

It should look like this:

```
from django.contrib import admin
from django.urls import path, include

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('treenav/', include('treenav.urls')),
```

**Comment by vkurup** [comment]
Sorry for the delay, but @itsdkey is now working on improving the sample project to support newer Django versions in #78
